server:
  port: 8999

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/team/**
        - id: player-service
          uri: lb://player-service
          predicates:
            - Path=/**